// apps/web/src/pages/details/DetailsPage.tsx
import { useCallback, useEffect, useState } from "react"
import { motion } from "framer-motion"
import {
  Clock3,
  Play,
  Plus,
  Check,
  Heart,
  Star,
  Calendar,
  Building2,
} from "lucide-react"
import { useNavigate, useParams } from "@tanstack/react-router"

import {
  getMovieDetailsBySlug,
  getTVDetailsBySlug,
  getCredits,
  getSimilar,
  getTVSeason,
} from "@/api/details"
import type { MovieDetails, CastMember, SimilarItem, Episode, SeasonInfo, ProductionCompany } from "@/api/details"

import { useWatchlist } from "@/stores/watchlist"
import { useLiked } from "@/stores/liked"
import { AmbientBackground } from "@/components/cinematic/AmbientBackground/AmbientBackground"
import { DetailsSkeleton } from "@/components/shared/LoadingSkeleton"

import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Separator } from "@/components/ui/separator"
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area"
import { cn } from "@/lib/utils"

export default function DetailsPage() {
  const navigate = useNavigate()
  const { type, slug } = useParams({
    from: "/details/$type/$slug",
  })

  const [movie, setMovie] = useState<MovieDetails | null>(null)
  const [cast, setCast] = useState<CastMember[]>([])
  const [similar, setSimilar] = useState<SimilarItem[]>([])
  const [selectedSeason, setSelectedSeason] = useState<number>(1)
  const [episodes, setEpisodes] = useState<Episode[]>([])
  const [error, setError] = useState<Error | null>(null)

  const addToWatchlist = useWatchlist((s) => s.add)
  const removeFromWatchlist = useWatchlist((s) => s.remove)
  const isInWatchlist = useWatchlist((s) => s.isInWatchlist)

  const toggleLiked = useLiked((s) => s.toggle)
  const isLiked = useLiked((s) => s.isLiked)

  const load = useCallback(async () => {
    try {
      setError(null)
      setMovie(null)
      setCast([])
      setSimilar([])
      setEpisodes([])

      const fn = type === "tv" ? getTVDetailsBySlug : getMovieDetailsBySlug
      const data = await fn(slug)
      setMovie(data)

      const id = String(data.id)
      const mediaType = data.mediaType || type
      const [creditsRes, similarRes] = await Promise.all([
        getCredits(id, mediaType).catch(() => null),
        getSimilar(id, mediaType).catch(() => null),
      ])

      if (creditsRes) setCast(creditsRes.cast.slice(0, 12))
      if (similarRes) setSimilar(similarRes.results.slice(0, 12))

      if (mediaType === "tv" && data.seasons && data.seasons.length > 0) {
        const firstSeason = data.seasons[0].seasonNumber
        setSelectedSeason(firstSeason)
        const seasonData = await getTVSeason(id, firstSeason).catch(() => null)
        if (seasonData) setEpisodes(seasonData.episodes)
      }
    } catch (err) {
      console.error(err)
      setError(err instanceof Error ? err : new Error("Failed to load details"))
    }
  }, [slug, type])

  useEffect(() => {
    load()
  }, [load])

  const loadSeason = useCallback(async (seasonNum: number) => {
    if (!movie) return
    setSelectedSeason(seasonNum)
    const seasonData = await getTVSeason(String(movie.id), seasonNum).catch(() => null)
    if (seasonData) setEpisodes(seasonData.episodes)
  }, [movie])

  if (error) {
    return (
      <main className="flex min-h-screen flex-col items-center justify-center bg-background text-foreground">
        <div className="text-center">
          <div className="mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-destructive/10">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-10 w-10 text-destructive">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="8" x2="12" y2="12" />
              <line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
          </div>
          <h2 className="text-2xl font-semibold">Failed to load details</h2>
          <p className="mt-3 text-muted-foreground">{error.message}</p>
          <Button onClick={load} className="mt-8 rounded-full px-8">
            Try Again
          </Button>
        </div>
      </main>
    )
  }

  if (!movie) {
    return <DetailsSkeleton />
  }

  const isTV = movie.mediaType === "tv"
  const seasons: SeasonInfo[] = movie.seasons || []

  return (
    <main className="relative min-h-screen overflow-hidden bg-background text-foreground">
      <AmbientBackground />

      {/* BACKDROP */}
      <div className="absolute inset-0">
        <img
          src={movie.backdropPath}
          alt={movie.title}
          loading="lazy"
          decoding="async"
          className="h-full w-full object-cover opacity-40"
        />
        <div className="absolute inset-0 bg-gradient-to-r from-background via-background/80 to-transparent" />
        <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-black/50" />
      </div>

      {/* CONTENT */}
      <section className="relative z-20 flex min-h-screen items-end px-6 pb-20 pt-32 md:px-16">
        <motion.div
          initial={{ opacity: 0, y: 60 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, ease: [0.22, 1, 0.36, 1] }}
          className="grid w-full gap-12 lg:grid-cols-[300px_1fr]"
        >
          {/* POSTER */}
          <div className="hidden lg:block">
            <img
              src={movie.posterPath}
              alt={movie.title}
              loading="lazy"
              decoding="async"
              className="w-full rounded-3xl border border-border shadow-2xl"
            />
          </div>

          {/* INFO */}
          <div className="max-w-3xl">
            {/* LOGO / TITLE */}
            {movie.logoPath ? (
              <img
                src={movie.logoPath}
                alt={movie.title}
                loading="lazy"
                decoding="async"
                className="mb-6 max-h-32 max-w-[380px] object-contain"
              />
            ) : (
              <h1 className="text-4xl font-semibold tracking-tight md:text-6xl lg:text-7xl">
                {movie.title}
              </h1>
            )}

            {/* META */}
            <div className="mb-6 mt-5 flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
              <div className="flex items-center gap-1.5">
                <Star size={14} className="text-primary" fill="currentColor" />
                <span className="text-foreground font-medium">{movie.rating.toFixed(1)}</span>
              </div>

              <Separator orientation="vertical" className="h-4" />

              {movie.runtime && (
                <div className="flex items-center gap-1.5">
                  <Clock3 size={14} />
                  <span>{movie.runtime}</span>
                </div>
              )}

              <Separator orientation="vertical" className="h-4" />

              <div className="flex items-center gap-1.5">
                <Calendar size={14} />
                <span>{movie.year}</span>
              </div>

              <Separator orientation="vertical" className="h-4" />

              <Badge variant="secondary" className="rounded-full">
                {movie.genres.join(" \u2022 ")}
              </Badge>

              {isTV && seasons.length > 0 && (
                <Badge variant="outline" className="rounded-full">
                  {seasons.length} Season{seasons.length > 1 ? "s" : ""}
                </Badge>
              )}
            </div>

            {/* PRODUCTION COMPANIES */}
            {movie.productionCompanies && movie.productionCompanies.length > 0 && (
              <div className="mb-6 flex flex-wrap items-center gap-3">
                <Building2 size={14} className="text-muted-foreground" />
                {movie.productionCompanies.map((company: ProductionCompany) => (
                  <a
                    key={company.id}
                    href={`https://www.themoviedb.org/company/${company.id}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group flex items-center gap-2 rounded-md border border-border bg-secondary/50 px-2.5 py-1.5 transition-colors hover:bg-secondary"
                  >
                    {company.logoPath ? (
                      <img
                        src={company.logoPath}
                        alt={company.name}
                        className="h-4 w-auto max-w-[70px] object-contain invert opacity-60 group-hover:opacity-100 transition-opacity"
                      />
                    ) : (
                      <span className="text-xs font-medium text-muted-foreground">{company.name}</span>
                    )}
                  </a>
                ))}
              </div>
            )}

            {/* OVERVIEW */}
            <p className="max-w-2xl text-base leading-7 text-muted-foreground md:text-lg md:leading-8">
              {movie.overview}
            </p>

            {/* ACTIONS */}
            <div className="mt-10 flex flex-wrap gap-3">
              <Button
                size="lg"
                className="rounded-full bg-gradient-to-r from-primary to-cyan-500 text-primary-foreground hover:opacity-90 gap-2 px-8"
                onClick={() => {
                  if (isTV) {
                    navigate({
                      to: "/watch/$type/$slug/$season/$episode",
                      params: { type: "tv", slug, season: "sn1", episode: "ep1" },
                    })
                  } else {
                    navigate({ to: "/watch/$type/$slug", params: { type: movie.mediaType || "movie", slug } })
                  }
                }}
              >
                <Play size={18} />
                Watch Now
              </Button>

              <Button
                size="lg"
                variant="outline"
                className={cn(
                  "rounded-full gap-2 px-6",
                  isInWatchlist(movie.id) && "border-green-500/30 bg-green-500/10 text-green-400 hover:bg-green-500/20 hover:text-green-400"
                )}
                onClick={() => {
                  if (isInWatchlist(movie.id)) {
                    removeFromWatchlist(movie.id)
                  } else {
                    addToWatchlist({
                      id: movie.id,
                      title: movie.title,
                      posterPath: movie.posterPath,
                      mediaType: movie.mediaType || "movie",
                      year: movie.year,
                    })
                  }
                }}
              >
                {isInWatchlist(movie.id) ? <Check size={18} /> : <Plus size={18} />}
                {isInWatchlist(movie.id) ? "In Watchlist" : "Watchlist"}
              </Button>

              <Button
                size="lg"
                variant="outline"
                className={cn(
                  "rounded-full h-11 w-11 p-0",
                  isLiked(movie.id) && "border-red-500/30 bg-red-500/10 text-red-400 hover:bg-red-500/20 hover:text-red-400"
                )}
                onClick={() =>
                  toggleLiked({
                    id: movie.id,
                    title: movie.title,
                    posterPath: movie.posterPath,
                    mediaType: movie.mediaType || "movie",
                    year: movie.year,
                  })
                }
              >
                <Heart size={18} fill={isLiked(movie.id) ? "currentColor" : "none"} />
              </Button>
            </div>
          </div>
        </motion.div>
      </section>

      <Separator className="relative z-20 mx-6 md:mx-16 bg-border/50" />

      {/* CAST */}
      {cast.length > 0 && (
        <section className="relative z-20 px-6 py-12 md:px-16">
          <h2 className="mb-6 text-xl font-semibold tracking-tight">Cast</h2>
          <ScrollArea className="w-full whitespace-nowrap">
            <div className="flex gap-4 pb-4">
              {cast.map((member) => (
                <div key={member.id} className="w-32 shrink-0 space-y-2">
                  <div className="aspect-[2/3] overflow-hidden rounded-xl bg-muted">
                    {member.profilePath ? (
                      <img
                        src={member.profilePath}
                        alt={member.name}
                        loading="lazy"
                        className="h-full w-full object-cover"
                      />
                    ) : (
                      <div className="flex h-full items-center justify-center text-muted-foreground/30">
                        <svg viewBox="0 0 24 24" fill="currentColor" width={32} height={32}>
                          <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
                        </svg>
                      </div>
                    )}
                  </div>
                  <p className="text-sm font-medium text-foreground truncate">{member.name}</p>
                  <p className="text-xs text-muted-foreground truncate">{member.character}</p>
                </div>
              ))}
            </div>
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        </section>
      )}

      {/* TV SEASONS & EPISODES */}
      {isTV && seasons.length > 0 && (
        <section className="relative z-20 px-6 py-12 md:px-16">
          <Tabs
            value={String(selectedSeason)}
            onValueChange={(v) => loadSeason(Number(v))}
            className="w-full"
          >
            <div className="flex items-center gap-4 mb-6">
              <h2 className="text-xl font-semibold tracking-tight">Episodes</h2>
              <TabsList className="rounded-full bg-secondary/50">
                {seasons.map((s) => (
                  <TabsTrigger
                    key={s.seasonNumber}
                    value={String(s.seasonNumber)}
                    className="rounded-full data-[state=active]:bg-foreground data-[state=active]:text-background text-xs px-3"
                  >
                    S{s.seasonNumber}
                  </TabsTrigger>
                ))}
              </TabsList>
            </div>

            <div className="grid gap-3">
              {episodes.map((ep) => (
                <div
                  key={ep.episodeNumber}
                  className="group flex gap-4 rounded-xl border border-border/50 bg-card/30 p-3 transition-all hover:bg-card/60 hover:border-border"
                >
                  <div className="w-40 shrink-0 overflow-hidden rounded-lg bg-muted aspect-video">
                    {ep.stillPath ? (
                      <img
                        src={ep.stillPath}
                        alt={ep.name}
                        loading="lazy"
                        className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                      />
                    ) : (
                      <div className="flex h-full items-center justify-center text-muted-foreground/30">
                        <Play size={24} />
                      </div>
                    )}
                  </div>
                  <div className="flex flex-1 flex-col justify-center min-w-0">
                    <div className="flex items-center gap-3">
                      <span className="text-sm font-semibold text-muted-foreground">E{ep.episodeNumber}</span>
                      <h3 className="text-sm font-medium text-foreground truncate">{ep.name}</h3>
                      {ep.runtime > 0 && (
                        <span className="text-xs text-muted-foreground shrink-0">{ep.runtime}m</span>
                      )}
                    </div>
                    <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{ep.overview}</p>
                  </div>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="shrink-0 self-center rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                    onClick={() => navigate({
                      to: "/watch/$type/$slug/$season/$episode",
                      params: { type: "tv", slug, season: "sn" + selectedSeason, episode: "ep" + ep.episodeNumber },
                    })}
                  >
                    <Play size={18} fill="currentColor" />
                  </Button>
                </div>
              ))}
            </div>
          </Tabs>
        </section>
      )}

      <Separator className="relative z-20 mx-6 md:mx-16 bg-border/50" />

      {/* SIMILAR */}
      {similar.length > 0 && (
        <section className="relative z-20 px-6 py-12 md:px-16 pb-24">
          <h2 className="mb-6 text-xl font-semibold tracking-tight">More Like This</h2>
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
            {similar.map((item) => (
              <div
                key={item.id}
                onClick={() => navigate({ to: "/details/$type/$slug", params: { type: item.mediaType, slug: item.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") } })}
                className="group cursor-pointer"
              >
                <div className="aspect-[2/3] overflow-hidden rounded-xl bg-muted">
                  {item.posterPath ? (
                    <img
                      src={item.posterPath}
                      alt={item.title}
                      loading="lazy"
                      className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                  ) : (
                    <div className="flex h-full items-center justify-center text-muted-foreground/30">
                      <svg viewBox="0 0 24 24" fill="currentColor" width={32} height={32}>
                        <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
                      </svg>
                    </div>
                  )}
                </div>
                <p className="mt-2 text-sm font-medium text-foreground/80 truncate">{item.title}</p>
                <p className="text-xs text-muted-foreground">{item.year}</p>
              </div>
            ))}
          </div>
        </section>
      )}
    </main>
  )
}

// frontend/src/components/DetailsPage.svelte
<script lang="ts">
  import { tmdbApi } from '../lib/api';

  // Props (Svelte 5 Runes)
  let { media = 'movie', id = '0' } = $props<{ media?: string; id?: string }>();

  // Type Interfaces
  interface Genre { id: number; name: string; }
  interface CastMember { name: string; character: string; profile_path: string; }
  interface Episode { name: string; episode_number: number; still_path: string; overview: string; }
  interface Season { season_number: number; episode_count: number; }
  
  interface MediaDetails {
    title?: string;
    name?: string;
    release_date?: string;
    first_air_date?: string;
    vote_average?: number;
    vote_count?: number;
    runtime?: number;
    number_of_seasons?: number;
    seasons?: Season[];
    genres?: Genre[];
    backdrop_path?: string;
    poster_path?: string;
    status?: string;
    tagline?: string;
    overview?: string;
    credits?: { cast: CastMember[] };
    videos?: { results: any[] };
  }

  // Reactive States
  let data: MediaDetails | null = $state(null);
  let loading = $state(true);
  let error = $state('');
  let selectedSeason = $state(1);
  let seasonEpisodes: Episode[] = $state([]);

  // Derived Values
  let mediaType = $derived(media === 'tv' ? 'tv' : 'movie');
  let title = $derived(data?.title || data?.name || '');
  let year = $derived((data?.release_date || data?.first_air_date || '').split('-')[0]);
  let rating = $derived(data?.vote_average ? (data.vote_average / 2).toFixed(1) : null);
  let runtime = $derived(
    data?.runtime ? `${Math.floor(data.runtime / 60)}h ${data.runtime % 60}m` : null
  );
  let seasons = $derived(
    (data?.seasons || []).filter((s) => s.season_number > 0 && s.episode_count > 0)
  );
  let cast = $derived((data?.credits?.cast || []).slice(0, 16));
  let genres = $derived(data?.genres || []);
  let backdropUrl = $derived(
    data?.backdrop_path ? `https://image.tmdb.org/t/p/original${data.backdrop_path}` : ''
  );
  let posterUrl = $derived(
    data?.poster_path ? `https://image.tmdb.org/t/p/w500${data.poster_path}` : ''
  );
  let votes = $derived(data?.vote_count || 0);
  let tagline = $derived(data?.tagline || '');

  // Synchronized Data Pipeline
  $effect(() => {
    const currentId = Number(id);
    if (!currentId) return;

    loading = true;
    error = '';
    data = null;
    selectedSeason = 1;
    seasonEpisodes = [];

    tmdbApi.details(mediaType, currentId)
      .then((res: any) => {
        data = res;
      })
      .catch(() => {
        error = 'Unable to synchronize title metadata.';
      })
      .finally(() => {
        loading = false;
      });
  });

  // Episodic Data Monitor
  $effect(() => {
    const currentId = Number(id);
    if (mediaType !== 'tv' || !data || !selectedSeason) return;

    tmdbApi.seasonEpisodes(currentId, selectedSeason)
      .then((res: any) => {
        seasonEpisodes = res.episodes || [];
      })
      .catch(() => {
        seasonEpisodes = [];
      });
  });

  function tmdbImg(path: string, size: string = 'w185'): string {
    return path ? `https://image.tmdb.org/t/p/${size}${path}` : '';
  }

  // Dynamic routing based on media type and context
  function watchUrl(episode?: number): string {
    if (mediaType === 'tv') {
      return `/watch/tv/${id}?season=${selectedSeason}&episode=${episode || 1}`;
    }
    return `/watch/movie/${id}`;
  }
</script>

<svelte:head>
  <title>{title ? `${title} — Watchfy` : 'Loading Details...'}</title>
</svelte:head>

{#if loading}
  <div class="min-h-screen bg-[#09090b] flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="max-w-7xl w-full mx-auto grid grid-cols-1 md:grid-cols-[280px_1fr] lg:grid-cols-[340px_1fr] gap-10 lg:gap-16 items-center animate-pulse pt-24">
      <div class="w-full aspect-[2/3] bg-zinc-900/60 rounded-2xl border border-zinc-800/40 hidden md:block"></div>
      <div class="space-y-6">
        <div class="flex gap-2"><div class="h-6 bg-zinc-900/80 rounded-md w-20"></div><div class="h-6 bg-zinc-900/80 rounded-md w-16"></div></div>
        <div class="h-12 bg-zinc-900/80 rounded-xl w-3/4"></div>
        <div class="h-4 bg-zinc-900/40 rounded w-1/2 italic"></div>
        <div class="space-y-2 pt-4">
          <div class="h-4 bg-zinc-900/60 rounded w-full"></div>
          <div class="h-4 bg-zinc-900/60 rounded w-5/6"></div>
        </div>
      </div>
    </div>
  </div>
{:else if error}
  <div class="min-h-screen flex items-center justify-center bg-[#09090b] px-4">
    <div class="text-center max-w-sm">
      <div class="w-14 h-14 rounded-2xl bg-red-500/10 border border-red-500/20 flex items-center justify-center text-red-500 mx-auto mb-4 backdrop-blur-xl shadow-xl shadow-red-500/5">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.75" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z" />
        </svg>
      </div>
      <h3 class="text-white font-bold text-lg mb-1">Something went wrong</h3>
      <p class="text-zinc-500 text-sm">{error}</p>
    </div>
  </div>
{:else}
  <div class="relative min-h-screen bg-[#09090b] text-zinc-100 overflow-hidden">
    
    {#if backdropUrl}
      <div class="absolute top-0 left-0 right-0 h-[85vh] w-full z-0 pointer-events-none overflow-hidden">
        <img src={backdropUrl} alt="" class="w-full h-full object-cover brightness-[0.22] scale-105 transition-transform duration-1000 motion-safe:scale-100" />
        <div class="absolute inset-0 bg-gradient-to-t from-[#09090b] via-[#09090b]/80 to-transparent"></div>
        <div class="absolute inset-0 bg-gradient-to-r from-[#09090b] via-[#09090b]/30 to-transparent"></div>
        <div class="absolute inset-0 bg-gradient-to-b from-[#09090b]/10 via-transparent to-[#09090b]"></div>
      </div>
    {/if}

    <div class="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-[16vh] md:pt-[24vh] pb-32">
      <div class="grid grid-cols-1 md:grid-cols-[240px_1fr] lg:grid-cols-[300px_1fr] gap-8 lg:gap-14 items-start">
        
        <div class="w-44 sm:w-56 md:w-full mx-auto md:mx-0 flex-shrink-0 relative group">
          <div class="aspect-[2/3] rounded-2xl overflow-hidden shadow-[0_25px_60px_-15px_rgba(0,0,0,0.9)] border border-zinc-800/60 bg-zinc-900 transition-all duration-500 group-hover:border-zinc-700/80 group-hover:shadow-black/100">
            {#if posterUrl}
              <img src={posterUrl} alt={title} class="w-full h-full object-cover select-none transition-transform duration-500 group-hover:scale-[1.02]" />
            {:else}
              <div class="w-full h-full flex flex-col items-center justify-center text-zinc-700 gap-3">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.25" stroke="currentColor" class="w-12 h-12">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5l4.72-4.72a.75.75 0 011.28.53v11.38a.75.75 0 01-1.28.53l-4.72-4.72M4.5 18.75h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25h-9A2.25 2.25 0 002.25 7.5v9a2.25 2.25 0 002.25 2.25z" />
                </svg>
                <span class="text-xs tracking-wider font-semibold uppercase opacity-60">No Media Poster</span>
              </div>
            {/if}
          </div>
        </div>

        <div class="text-center md:text-left mt-2 md:mt-0 flex flex-col">
          
          <div class="flex flex-wrap items-center justify-center md:justify-start gap-2 text-[11px] font-bold tracking-wide mb-4">
            <span class="bg-red-500/10 border border-red-500/30 text-red-400 px-3 py-1 rounded-lg uppercase font-extrabold tracking-widest shadow-sm shadow-red-500/5">
              {mediaType === 'tv' ? 'TV Series' : 'Movie'}
            </span>
            {#if year}
              <span class="bg-zinc-900/40 backdrop-blur-md px-3 py-1 rounded-lg border border-zinc-800/50 text-zinc-300">{year}</span>
            {/if}
            {#if runtime}
              <span class="bg-zinc-900/40 backdrop-blur-md px-3 py-1 rounded-lg border border-zinc-800/50 text-zinc-300">{runtime}</span>
            {/if}
            {#if mediaType === 'tv' && data?.number_of_seasons}
              <span class="bg-zinc-900/40 backdrop-blur-md px-3 py-1 rounded-lg border border-zinc-800/50 text-zinc-300">
                {data.number_of_seasons} {data.number_of_seasons === 1 ? 'Season' : 'Seasons'}
              </span>
            {/if}
            {#if rating}
              <span class="bg-zinc-900/40 backdrop-blur-md px-2.5 py-1 rounded-lg border border-zinc-800/50 flex items-center gap-1.5 text-amber-400">
                <svg class="w-3.5 h-3.5 fill-amber-400 drop-shadow-[0_0_4px_rgba(251,191,36,0.2)]" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg>
                {rating} <span class="text-zinc-500 text-[10px] font-medium">({votes.toLocaleString()})</span>
              </span>
            {/if}
          </div>

          <h1 class="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-[1.1] mb-2 drop-shadow-md">
            {title}
          </h1>

          {#if tagline}
            <p class="text-zinc-400 text-sm md:text-base font-medium italic mb-5 opacity-90">"{tagline}"</p>
          {/if}

          <div class="flex flex-wrap items-center justify-center md:justify-start gap-1.5 mb-6">
            {#each genres as genre}
              <a href="/search?genre={genre.id}" class="text-[11px] font-semibold px-3 py-1 rounded-full bg-zinc-900/30 hover:bg-zinc-800/60 text-zinc-400 hover:text-white border border-zinc-800/40 hover:border-zinc-700 transition-all duration-300">
                {genre.name}
              </a>
            {/each}
          </div>

          <div class="flex flex-wrap items-center justify-center md:justify-start gap-3 mb-8">
            <a
              href={watchUrl()}
              class="inline-flex items-center gap-2.5 px-8 py-3.5 bg-red-600 hover:bg-red-500 text-white text-sm font-bold rounded-xl transition-all duration-300 active:scale-95 shadow-xl shadow-red-600/20 hover:shadow-red-600/30 select-none"
            >
              <svg class="w-4 h-4 fill-white" viewBox="0 0 20 20"><path d="M6.423 4.167A1 1 0 005 5.035v9.93a1 1 0 001.423.868l8.5-4.965a1 1 0 000-1.736l-8.5-4.965z"/></svg>
              {mediaType === 'tv' ? `Play S${selectedSeason}:E1` : 'Play Title'}
            </a>
            
            <button class="inline-flex items-center gap-2 px-5 py-3.5 bg-zinc-900/40 backdrop-blur-md text-zinc-300 hover:text-white text-sm font-semibold rounded-xl border border-zinc-800/60 hover:bg-zinc-800/60 hover:border-zinc-700 transition-all duration-300 active:scale-95 cursor-pointer select-none">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.2" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
              </svg>
              My List
            </button>

            {#if data?.videos?.results?.length}
              <button class="inline-flex items-center gap-2 px-5 py-3.5 bg-zinc-900/40 backdrop-blur-md text-zinc-300 hover:text-white text-sm font-semibold rounded-xl border border-zinc-800/60 hover:bg-zinc-800/60 hover:border-zinc-700 transition-all duration-300 active:scale-95 cursor-pointer select-none">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M5.25 5.653c0-.856.917-1.398 1.667-.986l11.54 6.347a1.125 1.125 0 0 1 0 1.972l-11.54 6.347a1.125 1.125 0 0 1-1.667-.986V5.653Z" />
                </svg>
                Trailer
              </button>
            {/if}
          </div>

          {#if data?.overview}
            <div class="max-w-2xl mb-8 group text-balance">
              <h3 class="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-2.5 transition-colors group-hover:text-zinc-400">Overview</h3>
              <p class="text-zinc-300/90 text-sm leading-relaxed font-normal">
                {data.overview}
              </p>
            </div>
          {/if}

          {#if cast.length > 0}
            <div class="w-full">
              <h3 class="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-3.5">Top Billed Cast</h3>
              <div class="flex gap-4 overflow-x-auto pb-3 -mx-4 px-4 scrollbar-none select-none mask-image-r">
                {#each cast as person}
                  <div class="flex-shrink-0 w-20 text-center group/cast">
                    <div class="w-16 h-16 mx-auto rounded-full overflow-hidden bg-zinc-900 mb-2 ring-1 ring-zinc-800/80 transition-all duration-300 group-hover/cast:ring-zinc-600 group-hover/cast:scale-105 shadow-md">
                      {#if person.profile_path}
                        <img src={tmdbImg(person.profile_path, 'w185')} alt={person.name} class="w-full h-full object-cover transition-transform duration-300 group-hover/cast:scale-105" loading="lazy" />
                      {:else}
                        <div class="w-full h-full flex items-center justify-center bg-zinc-900 text-zinc-500 text-base font-bold">
                          {person.name.charAt(0)}
                        </div>
                      {/if}
                    </div>
                    <p class="text-[11px] text-zinc-200 font-semibold leading-tight truncate w-full group-hover/cast:text-white">{person.name}</p>
                    <p class="text-[10px] text-zinc-500 truncate w-full mt-0.5">{person.character || ''}</p>
                  </div>
                {/each}
              </div>
            </div>
          {/if}
        </div>
      </div>

      {#if mediaType === 'tv' && seasons.length > 0}
        <div class="mt-16 border-t border-zinc-900 pt-10">
          <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
            <div>
              <h2 class="text-xl font-extrabold text-white tracking-tight">Browse Episodes</h2>
              <p class="text-xs text-zinc-500 mt-0.5">Select a season to view details and availability.</p>
            </div>
            
            <div class="relative min-w-[160px]">
              <select
                bind:value={selectedSeason}
                class="appearance-none w-full bg-zinc-900/50 backdrop-blur-md text-zinc-200 text-xs font-bold px-4 py-2.5 pr-10 rounded-xl border border-zinc-800/60 hover:border-zinc-700 hover:text-white transition-all cursor-pointer focus:outline-none focus:ring-2 focus:ring-red-500/20"
              >
                {#each seasons as s}
                  <option value={s.season_number} class="bg-[#09090b] text-zinc-300">
                    Season {s.season_number} ({s.episode_count} eps)
                  </option>
                {/each}
              </select>
              <div class="absolute right-3.5 top-1/2 -translate-y-1/2 pointer-events-none text-zinc-500">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                  <path fill-rule="evenodd" d="M5.22 8.22a.75.75 0 0 1 1.06 0L10 11.94l3.72-3.72a.75.75 0 1 1 1.06 1.06l-4.25 4.25a.75.75 0 0 1-1.06 0L5.22 9.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
                </svg>
              </div>
            </div>
          </div>

          {#if seasonEpisodes.length > 0}
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
              {#each seasonEpisodes as ep}
                <a
                  href={watchUrl(ep.episode_number)}
                  class="group/ep flex flex-col rounded-2xl bg-zinc-900/20 hover:bg-zinc-900/40 border border-zinc-900/60 hover:border-zinc-800/80 transition-all duration-300 overflow-hidden shadow-sm"
                >
                  <div class="relative aspect-video w-full bg-zinc-900 overflow-hidden border-b border-zinc-950/40">
                    {#if ep.still_path}
                      <img src={tmdbImg(ep.still_path, 'w300')} alt={ep.name} class="w-full h-full object-cover transition-transform duration-500 group-hover/ep:scale-[1.03]" loading="lazy" />
                    {:else}
                      <div class="w-full h-full flex items-center justify-center bg-zinc-950/50">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-zinc-700">
                          <path fill-rule="evenodd" d="M4.5 5.653c0-1.426 1.529-2.33 2.779-1.643l11.54 6.347c1.295.712 1.295 2.573 0 3.286L7.28 19.99c-1.25.687-2.779-.218-2.779-1.643V5.653Z" clip-rule="evenodd" />
                        </svg>
                      </div>
                    {/if}
                    
                    <div class="absolute inset-0 bg-zinc-950/0 group-hover/ep:bg-zinc-950/30 transition-all duration-300 flex items-center justify-center backdrop-blur-[1px] opacity-0 group-hover/ep:opacity-100">
                      <div class="w-10 h-10 rounded-full bg-white/10 border border-white/20 flex items-center justify-center backdrop-blur-md shadow-xl text-white transform scale-90 group-hover/ep:scale-100 transition-transform duration-300">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4 translate-x-[1px]">
                          <path fill-rule="evenodd" d="M4.5 5.653c0-1.426 1.529-2.33 2.779-1.643l11.54 6.347c1.295.712 1.295 2.573 0 3.286L7.28 19.99c-1.25.687-2.779-.218-2.779-1.643V5.653Z" clip-rule="evenodd" />
                        </svg>
                      </div>
                    </div>
                    
                    <div class="absolute bottom-2 right-2 bg-black/75 backdrop-blur-md text-zinc-300 text-[10px] font-bold px-2 py-0.5 rounded-md border border-zinc-800/40 tracking-wider">
                      EP {String(ep.episode_number).padStart(2, '0')}
                    </div>
                  </div>

                  <div class="p-3.5 flex-1 flex flex-col min-w-0 bg-gradient-to-b from-transparent to-zinc-950/10">
                    <p class="text-xs text-zinc-200 group-hover/ep:text-white font-bold leading-snug line-clamp-1 transition-colors">
                      {ep.name || `Episode ${ep.episode_number}`}
                    </p>
                    {#if ep.overview}
                      <p class="text-[11px] text-zinc-500 mt-1.5 line-clamp-2 leading-relaxed font-normal">{ep.overview}</p>
                    {/if}
                  </div>
                </a>
              {/each}
            </div>
          {:else}
            <div class="text-center py-16 bg-zinc-900/10 rounded-2xl border border-zinc-900/50">
              <p class="text-xs text-zinc-500 animate-pulse font-medium tracking-wide">Assembling episodic index...</p>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </div>
{/if}

<style>
  /* Linear fade masking for top billed cast slider element */
  .mask-image-r {
    mask-image: linear-gradient(to right, rgba(0,0,0,1) 85%, rgba(0,0,0,0) 100%);
    -webkit-mask-image: linear-gradient(to right, rgba(0,0,0,1) 85%, rgba(0,0,0,0) 100%);
  }
</style>
