// frontend/src/components/Button.svelte
<script lang="ts">
  let { title, isActive = false, href = undefined } = $props();
  
  // Shared structural and interactive design tokens
  const baseStyles = "inline-flex items-center justify-center px-5 py-2.5 rounded-xl font-semibold text-sm transition-all duration-300 transform select-none focus:outline-none focus:ring-2 focus:ring-red-500/40 focus:ring-offset-2 focus:ring-offset-[#09090b]";
  
  const activeStyles = "bg-gradient-to-r from-red-600 to-pink-600 text-white shadow-lg shadow-red-600/20 hover:brightness-110 active:scale-[0.98]";
  
  const inactiveStyles = "bg-zinc-900/60 text-zinc-300 hover:text-white border border-zinc-800/80 hover:bg-zinc-800/80 hover:border-zinc-700/80 backdrop-blur-md active:scale-[0.98]";
  
  const elementStyles = `${baseStyles} ${isActive ? activeStyles : inactiveStyles}`;
</script>

{#if href}
  <a href={href} class={elementStyles}>
    {title}
  </a>
{:else}
  <button type="button" class={elementStyles}>
    {title}
  </button>
{/if}

// packages/ui-primitives/Button.tsx
import { ReactNode } from "react"

interface ButtonProps {
  children: ReactNode
  variant?: "primary" | "secondary" | "ghost"
  size?: "sm" | "md" | "lg"
  onClick?: () => void
  className?: string
}

export function Button({
  children,
  variant = "primary",
  size = "md",
  onClick,
  className = "",
}: ButtonProps) {
  const base = "inline-flex items-center justify-center rounded-full font-semibold transition-all duration-300"

  const variants = {
    primary:
      "bg-gradient-to-r from-[#8B5CF6] to-[#22D3EE] text-white hover:scale-105",
    secondary:
      "border border-white/10 bg-white/5 text-white/80 hover:bg-white/10 hover:text-white",
    ghost: "text-white/60 hover:text-white hover:bg-white/5",
  }

  const sizes = {
    sm: "px-4 py-2 text-sm",
    md: "px-6 py-3 text-base",
    lg: "px-8 py-4 text-lg",
  }

  return (
    <button
      onClick={onClick}
      className={`${base} ${variants[variant]} ${sizes[size]} ${className}`}
    >
      {children}
    </button>
  )
}
